// <auto-generated />
using System;
using DataAccessLayer.Concrete;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20221230091657_EducationColumDelete")]
    partial class EducationColumDelete
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EntityLayer.Concrete.Education", b =>
                {
                    b.Property<int>("EducationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("EducationArchive")
                        .HasColumnType("bit");

                    b.Property<string>("EducationContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EducationSchoolName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EducationSectionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EducationStartYear")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EducationStopYear")
                        .HasColumnType("datetime2");

                    b.HasKey("EducationID");

                    b.ToTable("Educations");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Experience", b =>
                {
                    b.Property<int>("ExperienceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("ExperienceArchive")
                        .HasColumnType("bit");

                    b.Property<string>("ExperienceCompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExperienceContext")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ExperienceContinue")
                        .HasColumnType("bit");

                    b.Property<string>("ExperienceJobName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExperienceStartYear")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExperienceStopYear")
                        .HasColumnType("datetime2");

                    b.HasKey("ExperienceID");

                    b.ToTable("Experiences");
                });

            modelBuilder.Entity("EntityLayer.Concrete.JobContent", b =>
                {
                    b.Property<int>("JobContentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("JobContentArchive")
                        .HasColumnType("bit");

                    b.Property<string>("JobContentInfo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("JobContentID");

                    b.ToTable("JobContents");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Summary", b =>
                {
                    b.Property<int>("SummaryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("SummaryArchive")
                        .HasColumnType("bit");

                    b.Property<string>("SummaryContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SummaryTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SummaryID");

                    b.ToTable("Summarys");
                });
#pragma warning restore 612, 618
        }
    }
}
